# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeCapacity < Formula
  desc "kube-capacity provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster"
  homepage "https://github.com/robscott/kube-capacity"
  version "0.7.4-rc3"
  license "apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/robscott/kube-capacity/releases/download/v0.7.4-rc3/kube-capacity_0.7.4-rc3_Darwin_arm64.tar.gz"
      sha256 "53e2d9eb2c2932502d36b4fb4097452d237e747b5e22e731a45cf9b5942d2cbd"

      def install
        bin.install "kube-capacity"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/robscott/kube-capacity/releases/download/v0.7.4-rc3/kube-capacity_0.7.4-rc3_Darwin_x86_64.tar.gz"
      sha256 "0b1ce976b10a45a7f59ffdc409139f94dfd1c2aaa05874859543cf5f725acbd6"

      def install
        bin.install "kube-capacity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/robscott/kube-capacity/releases/download/v0.7.4-rc3/kube-capacity_0.7.4-rc3_Linux_x86_64.tar.gz"
      sha256 "b9613d96f769189da5ebbc2ce925dd5abe284ef6bb48e04c5ed17ab012cc420e"

      def install
        bin.install "kube-capacity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robscott/kube-capacity/releases/download/v0.7.4-rc3/kube-capacity_0.7.4-rc3_Linux_arm64.tar.gz"
      sha256 "0e7dfe5dff797afb052d1d3643ed69ba11c1907008d51150211279b324a06fe0"

      def install
        bin.install "kube-capacity"
      end
    end
  end

  test do
    system "#{bin}/kube-capacity version"
  end
end
