# This file was generated by GoReleaser. DO NOT EDIT.
class KubeCapacity < Formula
  desc "kube-capacity provides an overview of the resource requests, limits, and utilization in a Kubernetes cluster"
  homepage ""
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/robscott/kube-capacity/releases/download/0.4.0/kube-capacity_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "62de6a14abb0ba968f08c20cad896fcc1845752f999b273491076c4fcd660a48"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/robscott/kube-capacity/releases/download/0.4.0/kube-capacity_0.4.0_Linux_x86_64.tar.gz"
      sha256 "5cca1740e8e89e0ae29a931050075c6225532a0b12d7c6d6e4c0ad5b84a8de2d"
    end
  end

  def install
    bin.install "kube-capacity"
  end

  test do
    system "#{bin}/kube-capacity version"
  end
end
